
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DIVIDE EQUAL LPAREN MINUS NUMBER PLUS PRINT RPAREN STRING TIMESexpression : expression PLUS term\n\t\t \t      | expression MINUS term\n\t\t \t      | expression EQUAL term\n\t\t\t      | STRING\n\t\t\t      | term\n   \t\t         term : term TIMES factor\n\t\t              | term DIVIDE factor\n\t\t\t      | factor\n\t\t\tprint : PRINT\n\t\t      \t      | PRINT expression \n\t\t              | PRINT factor \n\t\t              | PRINT NUMBER factor : NUMBERfactor : LPAREN expression RPAREN'
    
_lr_action_items = {'STRING':([0,6,],[3,3,]),'NUMBER':([0,6,7,8,9,10,11,],[5,5,5,5,5,5,5,]),'LPAREN':([0,6,7,8,9,10,11,],[6,6,6,6,6,6,6,]),'$end':([1,2,3,4,5,13,14,15,16,17,18,],[0,-5,-4,-8,-13,-1,-2,-3,-6,-7,-14,]),'PLUS':([1,2,3,4,5,12,13,14,15,16,17,18,],[7,-5,-4,-8,-13,7,-1,-2,-3,-6,-7,-14,]),'MINUS':([1,2,3,4,5,12,13,14,15,16,17,18,],[8,-5,-4,-8,-13,8,-1,-2,-3,-6,-7,-14,]),'EQUAL':([1,2,3,4,5,12,13,14,15,16,17,18,],[9,-5,-4,-8,-13,9,-1,-2,-3,-6,-7,-14,]),'RPAREN':([2,3,4,5,12,13,14,15,16,17,18,],[-5,-4,-8,-13,18,-1,-2,-3,-6,-7,-14,]),'TIMES':([2,4,5,13,14,15,16,17,18,],[10,-8,-13,10,10,10,-6,-7,-14,]),'DIVIDE':([2,4,5,13,14,15,16,17,18,],[11,-8,-13,11,11,11,-6,-7,-14,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,6,],[1,12,]),'term':([0,6,7,8,9,],[2,2,13,14,15,]),'factor':([0,6,7,8,9,10,11,],[4,4,4,4,4,16,17,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression PLUS term','expression',3,'p_operator','syntt.py',23),
  ('expression -> expression MINUS term','expression',3,'p_operator','syntt.py',24),
  ('expression -> expression EQUAL term','expression',3,'p_operator','syntt.py',25),
  ('expression -> STRING','expression',1,'p_operator','syntt.py',26),
  ('expression -> term','expression',1,'p_operator','syntt.py',27),
  ('term -> term TIMES factor','term',3,'p_operator','syntt.py',28),
  ('term -> term DIVIDE factor','term',3,'p_operator','syntt.py',29),
  ('term -> factor','term',1,'p_operator','syntt.py',30),
  ('print -> PRINT','print',1,'p_operator','syntt.py',31),
  ('print -> PRINT expression','print',2,'p_operator','syntt.py',32),
  ('print -> PRINT factor','print',2,'p_operator','syntt.py',33),
  ('print -> PRINT NUMBER','print',2,'p_operator','syntt.py',34),
  ('factor -> NUMBER','factor',1,'p_factor_num','syntt.py',63),
  ('factor -> LPAREN expression RPAREN','factor',3,'p_factor_expr','syntt.py',67),
]
